### ISSUE TITLE
What's the best way use/render partials?

### ISSUE THREAD

**Issue by Brunozrk** [bbatsov/rails-style-guide#127]
What's the best way to use/render partials?

    render partial: 'partial_name'
    render 'partial_name'

And with variables

    render 'partial_name', locals: { var: 'something' }
    render 'partial_name', var: 'something'

Sorry if it is a stupid question

**Comment by Brunozrk** [comment]
:+1:

**Comment by cesc1989** [comment]
Whenever I want to render a partial yielding a collection or an object, I need to specify the `partial:` word argument:

`<%= render partial: 'partial_name', collection: @collection %>`

If not, an exception is raised.

**Comment by onebree** [comment]
@cesc1989 yes, I get the same thing as well. I think this should be explained in the guide, or at least noted somewhere
