### ISSUE TITLE
Thoughts on Testing

### ISSUE THREAD

**Issue by cesc1989** [bbatsov/rails-style-guide#160]
Why there's no Testing section? Is it not necessary?

In [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide) there isn't a Testing section, too.

**Comment by onebree** [comment]
I consider testing a whole other realm. There is MUCH more variance in how people test. You have unit tests, integration tests, this that... Also, remember that Ruby/Rails testing frameworks are just DSLs written in Ruby (for the most part). You should have a good understanding of Ruby/Rails before even worrying about testing.

Just my two cents. If you are interested in RSpec best practices, check out [BetterSpecs.org][1]. I do not have a reference for other frameworks.

[1]: http://betterspecs.org/

**Comment by cesc1989** [comment]
I can understand that. Thanks @onebree

**Comment by bbatsov** [comment]
There used to be a testing section in the guide, but with so many frameworks and approaches out there I decided to drop it at some point.
