### ISSUE TITLE
Model class structure

### ISSUE THREAD

**Issue by agrimm** [bbatsov/rails-style-guide#165]
The Ruby Style Guide has a recommendation for class structures: https://github.com/bbatsov/ruby-style-guide#consistent-classes

Should there be one for the class of an ActiveRecord model?

**Comment by paudam** [comment]
I think this is quite enough, isn't it? https://github.com/bbatsov/rails-style-guide#activerecord

**Comment by agrimm** [comment]
Oops - I didn't see that!
