### ISSUE TITLE
Gemfile styling

### ISSUE THREAD

**Issue by mdkirby** [bbatsov/rails-style-guide#166]
There is a section for bundler, and I think there could be some more explicit rules for the Gemfile, though I don't know what the conventions are or what they should be. Some questions / suggestions below:

Whitespace for version locking, use the minimal amount of whitespace needed:
```
# bad
'short-gem',                                       '~> 2.0.1'
'really-long-gem-name-that-takes-forever-to-type', '~> 1.0.0'

# good
'short-gem', '~> 2.0.1'
'really-long-gem-name-that-takes-forever-to-type', '~> 1.0.0'
```

Ordering of gems and groups:  
1. Should the non-grouped gems always be listed first, or last?
2. Should the gems in the same group be ordered alphabetically, or put related gems together?
3. Should the groups themselves be alphabetical?

**Comment by paudam** [comment]
2. I would say order alphabetically, as there's usually more than one opinion on how gems are "related", plus you can use tools to order the list for you alphabetically :)

**Comment by ausmith** [comment]
Should general Gemfile suggestions maybe live in the [ruby-style-guide](https://github.com/bbatsov/ruby-style-guide) and just have the rails style guide reference that section of the ruby one?

**Comment by mdkirby** [comment]
@ausmith - that sounds like a good idea. I didn't see anything specifically mentioning the Gemfile in the ruby style guide either. 

https://github.com/bbatsov/ruby-style-guide/issues/520
