### ISSUE TITLE
`therubyracer` is never used in production

### ISSUE THREAD

**Issue by linesarefuzzy** [bbatsov/rails-style-guide#78]
You have `therubyracer` listed as a flawed gem because "the use of this gem in production is strongly discouraged as it uses a very large amount of memory." It's my understanding that [Rails uses the JS runtime only for minification](http://stackoverflow.com/questions/9673081/why-does-rails-require-javascript-runtime), meaning it's never used in production. That would be why in the Gemfile of a new Rails project it's included (commented out) in the `:assets` group. So it seems it really doesn't matter what runtime you choose. Am I mistaken?

Peace,
Fuzzy

**Comment by deivid-rodriguez** [comment]
@bbatsov This can now be closed :smiley:

**Comment by ausmith** [comment]
Agreed with @deivid-rodriguez now that #151 has been taken care of.
